language: android
android:
  components:
    - tools
    - platform-tools
    - android-27
    - build-tools-27
    - add-on
    - extra
licenses:
    - 'android-sdk-license-.+'
jdk:
    - oraclejdk8
script:
    - ./gradlew clean test --stacktrace
    - ./gradlew clean build connectedCheck -PdisablePreDex --stacktrace

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
      - chmod +x ./gradlew
      - yes | sdkmanager "platforms;android-27"
      - yes | sdkmanager "build-tools;27.0.0"
notifications:
  email: false