language: android
android:
  components:
    - tools
    - platform-tools
    - android-27
    - build-tools-27
    - add-on
    - extra
licenses:
  - 'android-sdk-license-.+'
jdk:
  - oraclejdk8
env:
  - TZ=Europe/Berlin
before_install:
  - chmod +x ./gradlew
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "build-tools;27.0.0"
before_script:
  - adb shell settings put global time_zone Europe/Berlin
script:
  - ./gradlew clean test --stacktrace
  - ./gradlew clean build connectedCheck -PdisablePreDex --stacktrace

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
notifications:
  email: false